config/routes.rb
Rails.application.routes.draw do
  get "/", to: "pages#home", as: "root"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"

  get "*path", to: "pages#not_found"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :breed
  enum sex: { female: 0, male: 1 }
  validates :title, :breed_id, :sex, :price, :deposit, :city, :state, :date_of_birth, presence: true
  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :set_listing, only: [:show, :edit, :update, :destroy]
    
    def index
        @listings = Listing.all
    end

    def show

    end

    def new
      @listing = Listing.new
    end

    def create
      if Listing.create(listing_params)
        p "success"
        redirect_to listings_path
      else
        render "new"
      end
        #finish logic for creating a record
    end

    def edit
      
    end

    def update
      if @listing.update(listing_params)
        p "success"
        redirect_to listings_path
      else
        p "failure"
        render "edit"
      end
        #finish logic for updating the record
    end

    def destroy

        #finish logic for deleting the record
    end

    private

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:title, :description, :breed_id, :sex, :price, :deposit, :city, :state, :date_of_birth, :diet, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        render plain: "home page"
    end

    def not_found
        render plain: "not found"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnakeMarketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with model:@listing, local: true do |form| %>
  <ul>
  
    <li>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </li>

    <li>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </li>

    <li>
      <%= form.label :breeds %>
      <%= form.collection_select(:breed_id, Breed.all, :id, :name) %>
    </li>

    <li>
      <%= form.label :sex %>
      <%= form.select(:sex, [['female', 'female'], ['male', 'male']]) %>
      <%=  %>
    </li>

    <li>
      <%= form.label :price %>
      <%= form.text_field :price %>
    </li>

    <li>
      <%= form.label :deposit %>
      <%= form.text_field :deposit %>
    </li>

    <li>
      <%= form.label :city %>
      <%= form.text_field :city %>
    </li>

    <li>
      <%= form.label :state %>
      <%= form.text_field :state %>
    </li>

    <li>
      <%= form.label :date_of_birth %>
      <%= form.date_select :date_of_birth %>
    </li>

    <li>
      <%= form.label :diet %>
      <%= form.text_field :diet %>
    </li>

    <li>
      <div>
        <%= form.label :picture %> 
        <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
      </div>
    </li>

    <li>
      <%= form.submit %>
    </li>

  </ul>

<% end %>

app/views/listings/edit.html.erb
<%= render "form" %>

app/views/listings/index.html.erb
<h1>Legless Pets</h1>

<div class="hero"></div>

<p>
  Find your dream snake
</p>

<h3><%= link_to "new listing", new_listing_path %></h3>

<% @listings.each do |i|%>

  <h3><%= i.title %>: <%= link_to "edit", edit_listing_path(i.id)  %></h3>
  <ul style=""> 
    <li><%= image_tag i.picture if i.picture.attached? %></li>
    <li><%= i.description %></li>
    <li><%= i.breed.name%></li>
    <li><%= i.sex %></li>
    <li><%= i.price %></li>
    <li><%= i.city %></li>
    <li><%= i.state %></li>
    <li><%= i.date_of_birth %></li>
    <li><%= i.diet %></li>
  </ul>

<% end %>

app/views/listings/new.html.erb
<%= render "form" %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/not_found.html.erb
<h1>Pages#not_found</h1>
<p>Find me in app/views/pages/not_found.html.erb</p>